version: '3.9'

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: Password12!
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  
  back:
    image: farming-backend:v4
    container_name: farming-backend
    build:
      context: ./Farming.Backend
      dockerfile: Dockerfile
    environment:
      - PostgreSql__ConnectionString=$DB_CONNECTION_STRING
      - Authorization__Secret=$AUTH_SECRET
    depends_on: 
      - postgres
    ports:
      - $BACKEND_PORT:80
    restart: unless-stopped

  front:
    image: farming-frontend:v4
    container_name: farming-frontend
    build:
      context: ./Farming.Frontend
      dockerfile: Dockerfile
    ports: 
      - $FRONTEND_PORT:80
    environment:
      - APIURL=$BACKEND_API_URL
    restart: unless-stopped

volumes:
  postgres:
    driver: local
